"""End-to-end tests for math_router command construction (Issue #257).

These cover two classes of route whose emitted CLI commands were unrunnable:

1. Autogenerated schema-backed routes with numeric positional args
   (e.g. ``mp_bernoulli 10``) discarded the extracted typed arg and
   re-passed the raw intent, failing at argparse.
2. The scratchpad ``chain`` route emitted a command missing the required
   ``--steps`` option.

Each bug gets a command-shape assertion plus a real-execution assertion so a
regression in either the argument mapping or the target script is caught.
"""

from __future__ import annotations

import json
import shlex
import subprocess
import sys
from pathlib import Path

import pytest

from scripts.cc_math import math_router

# Repo root: tests/ lives directly under it.
ROOT = Path(__file__).resolve().parents[1]


def _execute_routed_command(command: str) -> subprocess.CompletedProcess[str]:
    """Run a router-emitted command and return the completed process.

    The router emits ``uv run python <script> ...``. We swap the ``uv run
    python`` prefix for the active test interpreter so the real target script
    runs with the real emitted arguments without paying uv's resolution cost.
    ``shlex.split`` collapses the single-quoted ``--steps`` value into one
    argv token exactly as a shell would.
    """
    parts = shlex.split(command)
    assert parts[:3] == ["uv", "run", "python"], f"unexpected prefix: {parts[:3]}"
    argv = [sys.executable, *parts[3:]]
    return subprocess.run(
        argv,
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=120,
    )


# ---------------------------------------------------------------------------
# Bug 1 — autogenerated numeric positional routes
# ---------------------------------------------------------------------------


def test_autogenerated_numeric_positional_route_uses_typed_arg() -> None:
    """``mp_bernoulli 10`` must pass the extracted ``n`` (10), not the raw intent."""
    match = math_router.route("mp_bernoulli 10")

    assert match.script == "mpmath_compute.py"
    assert match.subcommand == "mp_bernoulli"
    # The bug echoed the raw intent as the positional (``mp_bernoulli "mp_bernoulli
    # 10"``) — the subcommand token must appear exactly once, not in the argument.
    assert match.command.count("mp_bernoulli") == 1
    # The extracted positional 10 is emitted (shlex.quote leaves a bare number bare).
    assert match.command.endswith("mp_bernoulli 10")


def test_autogenerated_numeric_positional_route_executes() -> None:
    """The emitted ``mp_bernoulli`` command runs and returns a real result."""
    match = math_router.route("mp_bernoulli 10")

    result = _execute_routed_command(match.command)

    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    # B_10 = 5/66 ≈ 0.0757575...
    assert "0.0757575" in json.dumps(payload)


def test_autogenerated_route_emits_extracted_schema_option() -> None:
    """An extracted schema OPTION (e.g. --k) is emitted, not silently dropped.

    Without this, ``mp_lambertw 2 k=1`` dropped ``--k`` and ran the default
    branch 0 instead of the requested branch 1.
    """
    match = math_router.route("mp_lambertw 2 k=1")

    assert match.subcommand == "mp_lambertw"
    assert "--k 1" in match.command

    result = _execute_routed_command(match.command)
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    # W(2) on the requested branch 1 is complex (-0.834...+4.53j); the default
    # branch 0 would be the real ~0.8526. The "j" proves --k 1 took effect.
    assert "j" in payload["result"]


def test_store_true_flag_option_emitted_without_value() -> None:
    """A store_true schema flag is emitted as a bare ``--name`` (no value)."""
    cmd_parts: list[str] = []
    specs = [
        {"name": "--regularized", "flag": True},
        {"name": "--k", "flag": False},
    ]
    math_router._append_schema_option_args(
        cmd_parts, specs, {"regularized": "1", "k": "3"}
    )

    assert cmd_parts == ["--regularized", "--k 3"]


# ---------------------------------------------------------------------------
# Bug 2 — scratchpad chain route
# ---------------------------------------------------------------------------


def test_scratchpad_chain_route_emits_steps_from_user_intent() -> None:
    """The chain route must emit ``--steps`` built from the user's own steps."""
    match = math_router.route("chain x = 2; x^2 = 4")

    assert match.script == "math_scratchpad.py"
    assert match.subcommand == "chain"
    assert "--steps" in match.command
    # The original bug emitted ``chain ""`` with no option.
    assert not match.command.rstrip().endswith('chain ""')
    # The emitted steps are the user's, not a hardcoded placeholder.
    assert "x = 2" in match.command
    assert "x^2 = 4" in match.command


def test_scratchpad_chain_route_reflects_distinct_user_steps() -> None:
    """A different chain must produce different steps — never a fixed placeholder.

    Guards against the regression where every chain emitted the hardcoded
    ``["x = 2", "x^2 = 4"]`` list, reporting a passing verification of a chain
    the user never requested.
    """
    match = math_router.route("chain a = 5; a^2 = 25")

    assert "a = 5" in match.command
    assert "a^2 = 25" in match.command
    # The placeholder from the first-pass implementation must not leak in.
    assert "x = 2" not in match.command


def test_scratchpad_chain_route_accepts_explicit_json_list() -> None:
    """An explicit, valid JSON list of steps is used verbatim (normalized)."""
    match = math_router.route('chain ["x = 1", "x + 1 = 2"]')

    assert match.subcommand == "chain"
    assert "--steps" in match.command
    assert "x = 1" in match.command
    assert "x + 1 = 2" in match.command

    result = _execute_routed_command(match.command)
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert [s.get("step") for s in payload.get("steps", [])] == ["x = 1", "x + 1 = 2"]


def test_scratchpad_chain_route_executes() -> None:
    """The emitted chain command runs and verifies the user's actual chain."""
    match = math_router.route("chain x = 2; x^2 = 4")

    result = _execute_routed_command(match.command)

    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload.get("all_valid") is True
    steps = payload.get("steps", [])
    assert [s.get("step") for s in steps] == ["x = 2", "x^2 = 4"]


# ---------------------------------------------------------------------------
# Fail-closed guards — never fabricate a chain or re-pass the raw intent
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "intent",
    [
        "chain",  # no steps at all
        "chain []",  # empty JSON list
        'chain ["x=2",]',  # malformed JSON (trailing comma)
        'chain {"a":1}',  # non-list JSON
        'chain ["", "   "]',  # blank string elements
        "chain [true, null]",  # non-string elements
    ],
)
def test_scratchpad_chain_route_fails_closed_on_unusable_steps(intent: str) -> None:
    """Unusable/malformed step payloads must not synthesize or fabricate a chain.

    A fabricated chain is worse than no command: it could report a passing
    verification of a chain the user never requested. So no ``--steps`` is
    emitted and the raw intent is not re-passed as a bogus positional.
    """
    match = math_router.route(intent)

    assert match.subcommand == "chain"
    assert "--steps" not in match.command
    # The command ends at the bare subcommand — no fabricated/echoed positional.
    assert match.command.rstrip().endswith("chain")


def test_scratchpad_chain_route_quotes_steps_against_shell_breakout() -> None:
    """A single quote in a chain step must not break out of the shell quoting.

    Without shlex.quote, ``chain x'$(id)' = y`` would emit
    ``--steps '["x'$(id)'..."]'`` where ``$(id)`` lands unquoted and would run
    if the command string were executed by a shell.
    """
    match = math_router.route("chain x'$(id)' = y; z = 1")

    assert match.subcommand == "chain"
    # The emitted command parses as a single safe argv — the payload survives
    # intact as literal data inside one --steps token (no extra/expanded args).
    parts = shlex.split(match.command)
    assert "--steps" in parts
    steps_value = parts[parts.index("--steps") + 1]
    assert "$(id)" in steps_value  # carried as inert text, not a shell token
    assert "$(id)" not in [p for p in parts if p != steps_value]


def test_schema_route_with_missing_positional_does_not_repass_raw_intent() -> None:
    """An incomplete schema-backed route must fail closed, not echo the intent."""
    match = math_router.route("mp_bernoulli")

    assert match.subcommand == "mp_bernoulli"
    # The bug would emit ``mp_bernoulli "mp_bernoulli"``; fail closed instead.
    assert '"mp_bernoulli"' not in match.command
    assert match.command.rstrip().endswith("mp_bernoulli")


# ---------------------------------------------------------------------------
# Regression guard — verify/explain still pass the step positional
# ---------------------------------------------------------------------------


def test_scratchpad_verify_route_still_passes_step_positional() -> None:
    """verify/explain must keep emitting a quoted positional, not ``--steps``."""
    match = math_router.route("verify step x + 1 = 2")

    assert match.script == "math_scratchpad.py"
    assert match.subcommand == "verify"
    assert "--steps" not in match.command
    # A quoted positional step is present.
    assert match.command.count('"') >= 2
