"""End-to-end tests for math_router command construction (Issue #257).

These cover two classes of route whose emitted CLI commands were unrunnable:

1. Autogenerated schema-backed routes with numeric positional args
   (e.g. ``mp_bernoulli 10``) discarded the extracted typed arg and
   re-passed the raw intent, failing at argparse.
2. The scratchpad ``chain`` route emitted a command missing the required
   ``--steps`` option.

Each bug gets a command-shape assertion plus a real-execution assertion so a
regression in either the argument mapping or the target script is caught.
"""

from __future__ import annotations

import json
import shlex
import subprocess
import sys
from pathlib import Path

from scripts.cc_math import math_router

# Repo root: tests/ lives directly under it.
ROOT = Path(__file__).resolve().parents[1]


def _execute_routed_command(command: str) -> subprocess.CompletedProcess[str]:
    """Run a router-emitted command and return the completed process.

    The router emits ``uv run python <script> ...``. We swap the ``uv run
    python`` prefix for the active test interpreter so the real target script
    runs with the real emitted arguments without paying uv's resolution cost.
    ``shlex.split`` collapses the single-quoted ``--steps`` value into one
    argv token exactly as a shell would.
    """
    parts = shlex.split(command)
    assert parts[:3] == ["uv", "run", "python"], f"unexpected prefix: {parts[:3]}"
    argv = [sys.executable, *parts[3:]]
    return subprocess.run(
        argv,
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=120,
    )


# ---------------------------------------------------------------------------
# Bug 1 — autogenerated numeric positional routes
# ---------------------------------------------------------------------------


def test_autogenerated_numeric_positional_route_uses_typed_arg() -> None:
    """``mp_bernoulli 10`` must pass the extracted ``n`` (10), not the raw intent."""
    match = math_router.route("mp_bernoulli 10")

    assert match.script == "mpmath_compute.py"
    assert match.subcommand == "mp_bernoulli"
    # The bug emitted the raw intent as the positional: ``mp_bernoulli "mp_bernoulli 10"``.
    assert '"mp_bernoulli 10"' not in match.command
    assert match.command.endswith('mp_bernoulli "10"')


def test_autogenerated_numeric_positional_route_executes() -> None:
    """The emitted ``mp_bernoulli`` command runs and returns a real result."""
    match = math_router.route("mp_bernoulli 10")

    result = _execute_routed_command(match.command)

    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    # B_10 = 5/66 ≈ 0.0757575...
    assert "0.0757575" in json.dumps(payload)


# ---------------------------------------------------------------------------
# Bug 2 — scratchpad chain route
# ---------------------------------------------------------------------------


def test_scratchpad_chain_route_emits_steps_from_user_intent() -> None:
    """The chain route must emit ``--steps`` built from the user's own steps."""
    match = math_router.route("chain x = 2; x^2 = 4")

    assert match.script == "math_scratchpad.py"
    assert match.subcommand == "chain"
    assert "--steps" in match.command
    # The original bug emitted ``chain ""`` with no option.
    assert not match.command.rstrip().endswith('chain ""')
    # The emitted steps are the user's, not a hardcoded placeholder.
    assert "x = 2" in match.command
    assert "x^2 = 4" in match.command


def test_scratchpad_chain_route_reflects_distinct_user_steps() -> None:
    """A different chain must produce different steps — never a fixed placeholder.

    Guards against the regression where every chain emitted the hardcoded
    ``["x = 2", "x^2 = 4"]`` list, reporting a passing verification of a chain
    the user never requested.
    """
    match = math_router.route("chain a = 5; a^2 = 25")

    assert "a = 5" in match.command
    assert "a^2 = 25" in match.command
    # The placeholder from the first-pass implementation must not leak in.
    assert "x = 2" not in match.command


def test_scratchpad_chain_route_executes() -> None:
    """The emitted chain command runs and verifies the user's actual chain."""
    match = math_router.route("chain x = 2; x^2 = 4")

    result = _execute_routed_command(match.command)

    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload.get("all_valid") is True
    steps = payload.get("steps", [])
    assert [s.get("step") for s in steps] == ["x = 2", "x^2 = 4"]


# ---------------------------------------------------------------------------
# Regression guard — verify/explain still pass the step positional
# ---------------------------------------------------------------------------


def test_scratchpad_verify_route_still_passes_step_positional() -> None:
    """verify/explain must keep emitting a quoted positional, not ``--steps``."""
    match = math_router.route("verify step x + 1 = 2")

    assert match.script == "math_scratchpad.py"
    assert match.subcommand == "verify"
    assert "--steps" not in match.command
    # A quoted positional step is present.
    assert match.command.count('"') >= 2
