-- Migration: Add surfaced_learning_ids to sessions (issue #228 item 2)
-- Already-surfaced filtering. The memory-awareness hook re-surfaces the same
-- top memories every turn. To suppress prior-turn picks BEFORE ranking, the
-- hook tracks the learning IDs it has already surfaced per session and passes
-- them to recall_learnings.py as --exclude-ids. This adds one nullable column:
--   surfaced_learning_ids -- the union (deduped, capped) of full learning UUIDs
--                            the hook has surfaced for this session. The hook
--                            reads/upserts it keyed on the PK `id`, which
--                            session-register sets to the stdin input.session_id
--                            (id == claude_session_id for registered sessions).
--
-- The column is nullable with NO default. ADD COLUMN with no default is a
-- metadata-only change in PostgreSQL 11+ (no table rewrite, no row locks), so
-- this is cheap on a populated table. A NULL means "nothing surfaced yet" and
-- is treated by the hook (COALESCE to '{}') as an empty exclusion set, so
-- pre-migration rows stay valid.
--
-- IF NOT EXISTS keeps the migration idempotent and safe to re-run. No new index
-- is needed: the hook's per-prompt read and upsert are point operations on the
-- PK `id` and use the existing sessions_pkey index.
--
-- Apply with `psql -f` (autocommit).

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS surfaced_learning_ids UUID[];
